### ISSUE TITLE
How do i use this?

### ISSUE THREAD

**Issue by frenchie7** [Asocia/rattrap#6]
I've tried reading on how to do use this gui but I've gotten nowhere. Would like to setup my G300s mouse

**Comment by sahinakkaya** [comment]
It requires python3.7 or greater and some other programs that needs to be installed on your system. 
Assuming that you are using an Ubuntu-like system, you can install the dependencies with:
`sudo apt install xev xmodmap`
And of course you need to download and compile _ratslap_ program. 
Then clone this project:
`git clone https://github.com/Asocia/rattrap.git`
Change the directory to _rattrap_ and install python dependencies with:
`pip3 install -r requirements.txt`
Then you should be able to run _rattrap_ with:
`python3 main.py`

Usage:

I think the UI is easy to understand. You just need to know when you click on "Capture shortcut" button, a window will open and wait for you to perform some operation. For example, if you want to assign Ctrl+X to some button, just press Ctrl+X when that window comes and it will automatically close. Then press OK and click Apply to apply all the changes.

**Comment by frenchie7** [comment]
Thank you. Do you know why i got

ModuleNotFoundError: No module named 'PyQt5'

**Comment by sahinakkaya** [comment]
Did you run the command that I mentioned at the previous message?
`pip3 install -r requirements.txt`
If so and you still get the same error message, try installing it with your system's package manager.
`sudo apt install python3-pyqt5`

**Comment by frenchie7** [comment]
Thank you sooo much. How do you create the desktop shortcut

**Comment by sahinakkaya** [comment]
No problem :) Glad that I can help.
Which OS are you using? Normally, **Settings -> Create shortcut on desktop** should work.

**Comment by frenchie7** [comment]
popOS based ubuntu 19.10

**Comment by sahinakkaya** [comment]
I wrote this program under Ubuntu 18.04 and desktop shortcut feature works fine on my system. I did a bit research about your system and I saw [some people complaining about adding desktop icons](https://www.reddit.com/r/pop_os/comments/bfrvqj/how_to_add_desktop_icons/). Since I'm not really sure what the problem is, I can't really help. Maybe you can try to do it on your own or if "Launch on startup" feature works fine, you can enable it so that you don't even need to click a desktop icon.
